# Reverse Linux VNC for GitHub Actions
# This YAML establishes the "build" workflow where we will execute all required scripts
# During the process, it should get stuck at the last step where it creates a new tunnel on ngrok.

name: Ubuntu
on: [push, workflow_dispatch]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing environment...
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      # legacy run command script-- run: ./scripts/configure-legacy.sh
      run: ./scripts/configure.sh
    - name: Starting VNC Server...
      env:
        VNC_SCREENSIZE: ${{ secrets.VNC_SCREENSIZE }}
        VNC_DEPTHVALUE: ${{ secrets.VNC_DEPTHVALUE }}
      # legacy run command-- run: cd $HOME && vncserver :1 -geometry $VNC_SCREENSIZE -depth $VNC_DEPTHVALUE -rfbport 7582
      run: export PATH=$PATH:/opt/TurboVNC/bin && cd $HOME && vncserver :1 -geometry $VNC_SCREENSIZE -depth $VNC_DEPTHVALUE -rfbport 7582
    - name: Creating tunnel with ngrok...
      run: sudo ./ngrok tcp 7582
      # legacy run command-- run: cd $HOME && vncserver :1 -geometry $VNC_SCREENSIZE -depth $VNC_DEPTHVALUE -rfbport 7582
    - name: ping Localhost.
      run: ping localhost
